name: missal_calculation
description: "The package that handles calculations for the daily and sunday readings"
version: 0.0.3
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0