enum MemorialEnum {
  mostHolyNameOfJesus("The Most Holy Name of Jesus"),
  saintsBasilGregory("Memorial of Saints Basil the Great and Gregory Nazianzen, Bishops and Doctors of the Church"),
  stElizabethAnnSeton("Memorial of Saint Elizabeth Ann Seton, Religious"),
  stJohnNeumann("Memorial of Saint John Neumann, Bishop"),
  stAndreBessette("Optional Memorial of Saint André Bessette, Religious"),
  stRaymondOfPenyafort("Optional Memorial of Saint Raymond of Penyafort, Priest"),
  stHilary("Optional Memorial of Saint Hilary, Bishop and Doctor of the Church"),
  stAntony("Memorial of Saint Anthony, Abbot"),
  stAgnesVirgin("Memorial of Saint Agnes, Virgin and Martyr"),
  stVincent("Optional Memorial of Saint Vincent, Deacon and Martyr"),
  stFrancisDeSales("Memorial of Saint Francis de Sales, Bishop and Doctor of the Church"),
  saintsTimothyAndTitus("Memorial of Saints Timothy and Titus, Bishops"),
  stAngelaMerici("Optional Memorial of Saint Angela Merici, Virgin"),
  stThomasAquinas("Memorial of Saint Thomas Aquinas, Priest and Doctor of the Church"),
  stJohnBosco("Memorial of Saint John Bosco, Priest"),
  stsFabianAndSebastian("Optional Memorial of Saint Fabian, Pope and Martyr; Optional Memorial of Saint Sebastian, Martyr"),
  stsVincentAndMarianneCope("Optional Memorial of Saint Vincent, Deacon and Martyr; Optional Memorial of Saint Marianne Cope, Virgin"),

  stAgathaVirgin("Memorial of Saint Agatha, Virgin and Martyr"),
  stPaulMikiAndCompanion("Memorial of Saint Paul Miki and Companions, Martyrs"),
  stJeromeOrStJosephine("Optional Memorial of Saint Jerome Emiliani, Priest; Optional Memorial of Saint Josephine Bakhita, Virgin"),
  stScholastica("Memorial of Saint Scholastica, Virgin"),
  ladyOfLourdes("Optional Memorial of Our Lady of Lourdes"),
  saintsCyrilMonkAndMethodius("Memorial of Saints Cyril, Monk, and Methodius, Bishop"),
  sevenHolyFounderOfServiteOrder("Optional Memorial of The Seven Holy Founders of the Servite Order"),
  stPeterDamian("Optional Memorial of Saint Peter Damian, Bishop and Doctor of the Church"),
  stPolycarp("Optional Memorial of Saint Polycarp, Bishop and Martyr"),
  stsBlaiseAndAnsgar("Optional Memorial of Saint Blaise, Bishop and Martyr; Optional Memorial of Saint Ansgar, Bishop"),
  stGregoryOfNarek("Optional Memorial of Saint Gregory of Narek, Abbot and Doctor of the Church"),

  stKatherineDrexel("Optional Memorial of Saint Katharine Drexel, Virgin"),
  stCasimir("Optional Memorial of Saint Casimir"),
  stsPerpetuaAndFelicity("Optional Memorial of Saints Perpetua and Felicity, Martyrs"),
  stJohnReligious("Optional Memorial of Saint John of God, Religious"),
  stFrancesRomeReligious("Optional Memorial of Saint Frances of Rome, Religious"),
  stPatrickBishop("Optional Memorial of Saint Patrick, Bishop"),
  stCyrilJerusalem("Optional Memorial of Saint Cyril of Jerusalem, Bishop and Doctor of the Church"),
  stTuribiusMongrovejo("Optional Memorial of Saint Toribio de Mogrovejo, Bishop"),

  stFrancisPaola("Optional Memorial Saint Francis of Paola, Hermit"),
  stIsidore("Optional Memorial Saint Isidore, Bishop and Doctor of the Church"),
  stVincentFerrer("Optional Memorial of Saint Vincent Ferrer, Priest"),
  stJohnBaptistDeLaSalle("Optional Memorial of Saint John Baptist de la Salle, Priest"),
  stStanislaus("Memorial of Saint Stanislaus, Bishop and Martyr"),
  stMartinI("Optional Memorial of Saint Martin I, Pope and Martyr"),
  stAnselm("Optional Memorial of Saint Anselm, Bishop and Doctor of the Church"),
  stGeorgeOrStAdalbert("Optional Memorial of Saint George, Martyr; Optional Memorial of Saint Adalbert, Bishop and Martyr"),
  stFidelisSigmaringen("Optional Memorial of St Fidelis of Sigmaringen, Priest, Martyr"),
  stPeterChanelOrStLouisMaryDeMontfort("Optional Memorial of Saint Peter Chanel, Priest and Martyr; Optional Memorial of Saint Louis Grignion de Montfort, Priest"),
  stCatherineSiena("Memorial of Saint Catherine of Siena, Virgin and Doctor of the Church"),
  stPiusV("Optional Memorial of Saint Pius V, Pope, Religious"),

  stJosephTheWorker("Optional Memorial of Saint Joseph the Worker"),
  stAthanasius("Memorial of Saint Athanasius, Bishop and Doctor of the Church"),
  stJohnAvila("Optional Memorial of John of Avila, Priest and Doctor of the Church"),
  stsJohnAndDamienJoseph("Optional Memorial of John of Avila, Priest and Doctor of the Church; Optional Memorial of Saint Damien Joseph de Veuster of Moloka'i, Priest"),
  stsNereusAndAchilleus("Optional Memorial of Saints Nereus and Achilleus, Martyrs; Optional Memorial of Saint Pancras, Martyr"),
  stIsidoreTheFarmer("Optional Memorial of Saint Isidore the Farmer"),
  ladyOfFatima("Optional Memorial of Our Lady of Fatima"),
  stJohnI("Optional Memorial of Saint John I, Pope, Martyr"),
  stBernadineOfSiena("Optional Memorial of Saint Bernardine of Siena, Priest"),
  stChristopherMagallanes("Optional Memorial of Saint Christopher Magallanes, Priest, and Companions, Martyrs"),
  stRitaCascia("Optional Memorial of Saint Rita of Cascia, Religious"),
  stsBedeGregoryAndMary("Optional Memorial of Saint Bede the Venerable, Priest and Doctor of the Church; Optional Memorial of Saint Gregory VII, Pope, Religious; Optional Memorial of Saint Mary Magdalene de’ Pazzi, Virgin"),
  stPhilipNeri("Memorial of Saint Philip Neri, Priest"),
  stAugustineCanterbury("Optional Memorial of Saint Augustine of Canterbury, Bishop"),
  stPaulVI("Optional Memorial of Saint Paul VI, Pope"),

  stJustin("Memorial of Saint Justin, Martyr"),
  stsMarcellinusAndPeter("Optional Memorial of Saints Marcellinus and Peter, Martyrs"),
  stCharlesLwangaAndCompanions("Memorial of Saint Charles Lwanga and companions, Martyrs"),
  stBoniface("Memorial of Saint Boniface, Bishop and Martyr"),
  stNorbert("Optional Memorial of Saint Norbert, Bishop"),
  stEphrem("Optional Memorial of Saint Ephrem, Deacon and Doctor of the Church"),
  stBarnabas("Memorial of Saint Barnabas, Apostle"),
  stAnthonyPadua("Memorial of Saint Anthony of Padua, Priest and Doctor of the Church"),
  stRomuald("Optional Memorial of Saint Romuald, Abbot"),
  stAloysiusGonzaga("Memorial of Saint Aloysius Gonzaga, Religious"),
  stsPaulinusJohnAndThomas("Optional Memorial of Saint Paulinus of Nola, Bishop; Optional Memorial of Saint John Fisher, Bishop and Martyr and Saint Thomas More, Martyr"),
  stCyrilAlexandria("Optional Memorial of Saint Cyril of Alexandria, Bishop and Doctor of the Church"),
  stIrenaeus("Memorial of Saint Irenaeus, Bishop and Martyr"),
  firstHolyMartyrs("Optional Memorial of the First Holy Martyrs of the Holy Roman Church"),

  stJuniperoSerra("Optional Memorial of Saint Junipero Serra, Priest"),
  usIndependenceDay("Independence Day"),
  stAnthonyMaryZaccaria("Optional Memorial of Saint Anthony Mary Zaccaria, Priest"),
  stsElizabethAndAnthony("Optional Memorial of Saint Anthony Mary Zaccaria, Priest; Optional Memorial of Saint Elizabeth of Portugal"),
  stMariaGoretti("Optional Memorial of Saint Maria Goretti, Virgin and Martyr"),
  stAugustineZhaoAndCompanions("Optional Memorial of Saint Augustine Zhao Rong, Priest, and Companions, Martyrs"),
  stBenedictAbbot("Memorial of Saint Benedict, Abbot"),
  stHenry("Optional Memorial of Saint Henry"),
  stKateriTekakwitha("Memorial of Saint Kateri Tekakwitha, Virgin"),
  stBonaventure("Memorial of Saint Bonaventure, Bishop and Doctor of the Church"),
  ladyOfCarmel("Optional Memorial of Our Lady of Mount Carmel"),
  stCamillusDeLellis("Optional Memorial of Saint Camillus de Lellis, Priest"),
  stApollinaris("Optional Memorial of Saint Apollinaris, Bishop and Martyr"),
  stLawrenceBrindisi("Optional Memorial of Saint Lawrence of Brindisi, Priest and Doctor of the Church"),
  stBridgetSweden("Optional Memorial of Saint Bridget of Sweden, Religious"),
  stSharbel("Optional Memorial of Saint Sharbel Makhlūf, Priest"),
  stsJoachimAndAnne("Memorial of Saints Joachim and Anne, Parents of the Blessed Virgin Mary"),
  stsMarthaMaryAndLazarus("Memorial of Saints Martha, Mary, and Lazarus"),
  stPeterChrysologus("Optional Memorial of Saint Peter Chrysologus, Bishop and Doctor of the Church"),
  stIgnatiusOfLoyola("Memorial of Saint Ignatius of Loyola, Priest"),

  stAlphonsusLiguori("Memorial of Saint Alphonsus Liguori, Bishop and Doctor of the Church"),
  stsJulianAndEusebius("Optional Memorial of Saint Eusebius of Vercelli, Bishop; Optional Memorial of Saint Peter Julian Eymard, Priest"),
  stJohnVianney("Memorial of Saint John Vianney, Priest"),
  dedicationOfSaintMaryMajorBasilica("Optional Memorial of the Dedication of the Basilica of Saint Mary Major in Rome"),
  stsSixtusAndCajetan("Optional Memorial of Saint Sixtus II, Pope and Martyr, and Companions, Martyrs; Optional Memorial of Saint Cajetan, Priest"),
  stDominic("Memorial of Saint Dominic, Priest"),
  stTeresaBenedicta("Optional Memorial of Saint Teresa Benedicta of the Cross, Virgin and Martyr"),
  stClare("Memorial of Saint Clare, Virgin"),
  stJaneFrancesDeChantal("Optional Memorial of Saint Jane Frances de Chantal, Religious"),
  stsPontianAndHippolytus("Optional Memorial of Saint Pontian, Pope and Martyr, and Saint Hippolytus, Priest and Martyr"),
  stMaximillianKolbe("Memorial of Saint Maximilian Kolbe, Priest and Martyr"),
  stStephenOfHungary("Optional Memorial of Saint Stephen of Hungary"),
  stJohnEudes("Optional Memorial of Saint John Eudes, Priest"),
  stBernard("Memorial of Saint Bernard, Abbot and Doctor of the Church"),
  stPiusX("Memorial of Saint Pius X, Pope"),
  queenshipOfBVM("Memorial of the Queenship of the Blessed Virgin Mary"),
  stRoseOfLima("Optional Memorial of Saint Rose of Lima, Virgin"),
  stsLouisAndJoseph("Optional Memorial of Saint Louis of France; Optional Memorial of Saint Joseph Calasanz, Priest"),
  stMonica("Memorial of Saint Monica"),
  stAugustine("Memorial of Saint Augustine, Bishop and Doctor of the Church"),
  passionOfStJohnTheBaptist("Memorial of the Passion of Saint John the Baptist"),

  stGregoryTheGreat("Memorial of Saint Gregory the Great, Pope and Doctor of the Church"),
  stPeterClaver("Memorial of Saint Peter Claver, Priest"),
  mostHolyNameOfMary("Memorial of the Most Holy Name of Mary"),
  stJohnChrysostom("Memorial of Saint John Chrysostom, Bishop and Doctor of the Church"),
  ladyOfSorrows("Memorial of Our Lady of Sorrows"),
  stsCorneliusAndCyprian("Memorial of Saints Cornelius, Pope, and Cyprian, Bishop, Martyrs"),
  stsHildegardAndRobert("Optional Memorial of Saint Hildegard of Bingen, Virgin and Doctor of the Church; Optional Memorial of Saint Robert Bellarmine, Bishop and Doctor of the Church"),
  stJanuarius("Optional Memorial of Saint Januarius, Bishop and Martyr"),
  stsAndrewAndPaulAndCompanions("Memorial of Saints Andrew Kim Tae-gŏn, Priest, and Paul Chŏng Ha-sang, and Companions, Martyrs"),
  stPiusOfPietrelcina("Memorial of Saint Pius of Pietrelcina, Priest"),
  stsCosmasAndDamian("Optional Memorial of Saints Cosmas and Damian, Martyrs"),
  stVincentDePaul("Memorial of Saint Vincent de Paul, Priest"),
  stsWenceslausAndLawrenceAndCompanions("Optional Memorial of Saint Wenceslaus, Martyr; Optional Memorial of Saint Lawrence Ruiz and companions, Martyrs"),
  stJerome("Memorial of Saint Jerome, Priest and Doctor of the Church"),

  stTherese("Memorial of Saint Thérèse of the Child Jesus, Virgin and Doctor of the Church"),
  holyGuardianAngels("Memorial of the Holy Guardian Angels"),
  stFrancisOfAssisi("Memorial of Saint Francis of Assisi"),
  blessedFrancisXavierAndFaustina("Optional Memorial of Saint Faustina Kowalska, Virgin; Optional Memorial of Blessed Francis Xavier Seelos, Priest"),
  stFaustinaKowalska("Optional Memorial of Saint Faustina Kowalska, Virgin"),
  stBruno("Optional Memorial of Saint Bruno, Priest"),
  blessedMarieRoseDurocherAndStBruno("Optional Memorial of Saint Bruno, Priest; Optional Memorial of Blessed Marie-Rose Durocher, Virgin"),
  ladyOfTheRosary("Memorial of Our Lady of the Rosary"),
  stsJohnAndDenisAndCompanions("Optional Memorial of Saint Denis, Bishop and Martyr, and his Companions, Martyrs; Optional Memorial of Saint John Leonardi, Priest"),
  stJohnXXIII("Optional Memorial of Saint John XXIII, Pope"),
  stCallistusI("Optional Memorial of Saint Callistus I, Pope and Martyr"),
  stTeresaOfJesus("Memorial of Saint Teresa of Jesus, Virgin and Doctor of the Church"),
  stsMargaretAndHedwig("Optional Memorial of Saint Hedwig, Religious; Optional Memorial of Saint Margaret Mary Alacoque, Virgin"),
  stIgnatiusOfAntioch("Memorial of Saint Ignatius of Antioch, Bishop and Martyr"),
  stsJohnAndIsaac("Memorial of Saints John de Brébeuf and Isaac Jogues, Priests, and Companions, Martyrs"),
  stPaulOfTheCross("Optional Memorial of Saint Paul of the Cross, Priest"),
  stJohnPaulII("Optional Memorial of Saint John Paul II, Pope"),
  stJohnOfCapistrano("Optional Memorial of Saint John of Capistrano, Priest"),
  stAnthonyMaryClaret("Optional Memorial of Saint Anthony Mary Claret, Bishop"),

  stMartinDePorres("Optional Memorial of Saint Martin de Porres, Religious"),
  stCharlesBorromeo("Memorial of Saint Charles Borromeo, Bishop"),
  stLeoTheGreat("Memorial of Saint Leo the Great, Pope and Doctor of the Church"),
  stMartinOfTours("Memorial of Saint Martin of Tours, Bishop"),
  stJosaphat("Memorial of Saint Josaphat, Bishop and Martyr"),
  stFrancesXavier("Memorial of Saint Frances Xavier Cabrini, Virgin"),
  stAlbertTheGreat("Optional Memorial of Saint Albert the Great, Bishop and Doctor of the Church"),
  stsMargaretAndGertrude("Optional Memorial of Saint Margaret of Scotland; Optional Memorial of Saint Gertrude, Virgin"),
  stElizabethOfHungary("Memorial of Saint Elizabeth of Hungary, Religious"),
  stRosePhilippine("Optional Memorial of Saint Rose Philippine Duchesne, Virgin"),
  presentationOfBVM("Memorial of the Presentation of the Blessed Virgin Mary"),
  stCecilia("Memorial of Saint Cecilia, Virgin and Martyr"),
  stsMiguelAndColumbanAndClementI("Optional Memorial of Saint Clement I, Pope and Martyr; Optional Memorial of Saint Columban, Abbot"),
  stsMiguelAndColumbanAndClementIAndBlessedMiguel("Optional Memorial of Saint Clement I, Pope and Martyr; Optional Memorial of Saint Columban, Abbot; Optional Memorial of Blessed Miguel Agustín Pro, Priest and Martyr"),
  stAndrewDungLac("Memorial of Saint Andrew Dŭng-Lạc, Priest, and Companions, Martyrs"),
  stCatherineOfAlexandria("Optional Memorial of Saint Catherine of Alexandria, Virgin and Martyr"),

  stXavier("Memorial of Saint Francis Xavier, Priest"),
  stJohnOfDamascus("Optional Memorial of Saint John of Damascus, Priest and Doctor of the Church"),
  stNicholas("Optional Memorial of Saint  Nicholas, Bishop"),
  stAmbrose("Memorial of Saint Ambrose, Bishop and Doctor of the Church"),
  stJuanDiego("Optional Memorial of Saint Juan Diego Cuauhtlatoatzin"),
  ladyOfLoreto("Optional Memorial of Our Lady of Loreto"),
  stDamasusI("Optional Memorial of Saint Damasus I, Pope"),
  stLucy("Memorial of Saint Lucy, Virgin and Martyr"),
  stJohnOfTheCross("Memorial of Saint John of the Cross, Priest and Doctor of the Church"),
  stPeterCanisius("Optional Memorial of Saint Peter Canisius, Priest and Doctor of the Church"),
  stJohnOfKanty("Optional Memorial of Saint John of Kanty, Priest"),
  stThomasBecket("Optional Memorial of Saint Thomas Becket, Bishop and Martyr"),
  stSylvesterI("Optional Memorial of Saint Sylvester I, Pope"),

  memBVMMother("Memorial of the Blessed Virgin Mary, Mother of the Church"),
  immaculateHeartBVM("Memorial of the Immaculate Heart of the Blessed Virgin Mary");

  final String title;
  const MemorialEnum(this.title);
}
