DateTime kdtNativityOfStJohnTheBaptist(int year) => DateTime(year, 6, 24);
DateTime kdtSSPeterAndPaul(int year) => DateTime(year, 6, 29);

DateTime kdtBasilAndGregory(int year) => DateTime(year, 1, 2);
DateTime kdtMostHolyName(int year) => DateTime(year, 1, 3);
DateTime kdtStElizabethAnnSeton(int year) => DateTime(year, 1, 4);
DateTime kdtStJohnNeumann(int year) => DateTime(year, 1, 5);
DateTime kdtStAndreBessette(int year) => DateTime(year, 1, 6);
DateTime kdtStRaymondOfPenyafort(int year) => DateTime(year, 1, 7);
DateTime kdtSaintHilary(int year) => DateTime(year, 1, 13);
DateTime kdtMemorialSaintAntony(int year) => DateTime(year, 1, 17);
DateTime kdtBlessedTansi(int year) => DateTime(year, 1, 20);
DateTime kdtStsFabianAndSebastian(int year) => DateTime(year, 1, 20);
DateTime kdtMemorialSaintAgnesVirgin(int year) => DateTime(year, 1, 21);
DateTime kdtMemorialSaintVincent(int year) => DateTime(year, 1, 22);
DateTime kdtStsVincentAndMarianneCope(int year) => DateTime(year, 1, 23);
DateTime kdtMemorialSaintFrancesDeSales(int year) => DateTime(year, 1, 24);
DateTime kdtConversionOfSaintPaul(int year) => DateTime(year, 1, 25);
DateTime kdtSaintsTimothyAndTitus(int year) => DateTime(year, 1, 26);
DateTime kdtSaintAngelaMerici(int year) => DateTime(year, 1, 27);
DateTime kdtSaintThomasAquinas(int year) => DateTime(year, 1, 28);
DateTime kdtSaintJohnBosco(int year) => DateTime(year, 1, 31);

DateTime kdtStsBlaiseAndAnsgar(int year) => DateTime(year, 2, 3);
DateTime kdtStAgathaVirgin(int year) => DateTime(year, 2, 5);
DateTime kdtStPaulMikiAndCompanion(int year) => DateTime(year, 2, 6);
DateTime kdtStJeromeOrJosephine(int year) => DateTime(year, 2, 8);
DateTime kdtStScholastica(int year) => DateTime(year, 2, 10);
DateTime kdtLadyOfLourdes(int year) => DateTime(year, 2, 11);
DateTime kdtSaintsCyrilMonkAndMethodius(int year) => DateTime(year, 2, 14);
DateTime kdtSevenHolyFounderOfServiteOrder(int year) => DateTime(year, 2, 17);
DateTime kdtStPeterDamian(int year) => DateTime(year, 2, 21);
DateTime kdtChairOfSaintPeter(int year) => DateTime(year, 2, 22);
DateTime kdtStPolycarp(int year) => DateTime(year, 2, 23);
DateTime kdtStGregoryOfNarek(int year) => DateTime(year, 2, 27);

DateTime kdtStKatherineDrexel(int year) => DateTime(year, 3, 3);
DateTime kdtStCasimir(int year) => DateTime(year, 3, 4);
DateTime kdtStsPerpetuaAndFelicity(int year) => DateTime(year, 3, 7);
DateTime kdtStJohnReligious(int year) => DateTime(year, 3, 8);
DateTime kdtStFrancesRomeReligious(int year) => DateTime(year, 3, 9);
DateTime kdtStPatrickBishop(int year) => DateTime(year, 3, 17);
DateTime kdtStCyrilJerusalem(int year) => DateTime(year, 3, 18);
DateTime kdtStTuribiusMongrovejo(int year) => DateTime(year, 3, 23);

DateTime kdtStFrancisPaola(int year) => DateTime(year, 4, 2);
DateTime kdtStIsidore(int year) => DateTime(year, 4, 4);
DateTime kdtStVincentFerrer(int year) => DateTime(year, 4, 5);
DateTime kdtStJohnBaptistDeLaSalle(int year) => DateTime(year, 4, 7);
DateTime kdtStStanislaus(int year) => DateTime(year, 4, 11);
DateTime kdtStMartinI(int year) => DateTime(year, 4, 13);
DateTime kdtStAnselm(int year) => DateTime(year, 4, 21);
DateTime kdtStGeorgeOrStAdalbert(int year) => DateTime(year, 4, 23);
DateTime kdtStFidelisSigmaringen(int year) => DateTime(year, 4, 24);
DateTime kdtStMark(int year) => DateTime(year, 4, 25);
DateTime kdtStPeterChanelOrStLouisMaryDeMontfort(int year) => DateTime(year, 4, 28);
DateTime kdtStCatherine(int year) => DateTime(year, 4, 29);
DateTime kdtOurLadyMotherOfAfrica(int year) => DateTime(year, 4, 30);
DateTime kdtStPiusV(int year) => DateTime(year, 4, 30);

DateTime kdtStJosephTheWorker(int year) => DateTime(year, 5, 1);
DateTime kdtStAthanasius(int year) => DateTime(year, 5, 2);
DateTime kdtStsPhilipAndJames(int year) => DateTime(year, 5, 3);
DateTime kdtStJohnAvila(int year) => DateTime(year, 5, 10);
DateTime kdtStsNereusAndAchilleus(int year) => DateTime(year, 5, 12);
DateTime kdtLadyOfFatima(int year) => DateTime(year, 5, 13);
DateTime kdtStMatthias(int year) => DateTime(year, 5, 14);
DateTime kdtStIsidoreTheFarmer(int year) => DateTime(year, 5, 15);
DateTime kdtStJohnI(int year) => DateTime(year, 5, 18);
DateTime kdtStBernadineOfSiena(int year) => DateTime(year, 5, 20);
DateTime kdtStChristopherMagallanes(int year) => DateTime(year, 5, 21);
DateTime kdtStRitaCascia(int year) => DateTime(year, 5, 22);
DateTime kdtStsBedeGregoryAndMary(int year) => DateTime(year, 5, 25);
DateTime kdtStPhilipNeri(int year) => DateTime(year, 5, 26);
DateTime kdtStAugustineCanterbury(int year) => DateTime(year, 5, 27);
DateTime kdtStPaulVI(int year) => DateTime(year, 5, 29);
DateTime kdtVisitationOfBVM(int year) => DateTime(year, 5, 31);

DateTime kdtStJustin(int year) => DateTime(year, 6, 1);
DateTime kdtStsMarcellinusAndPeter(int year) => DateTime(year, 6, 2);
DateTime kdtStCharlesLwangaAndCompanions(int year) => DateTime(year, 6, 3);
DateTime kdtStBoniface(int year) => DateTime(year, 6, 5);
DateTime kdtStNorbert(int year) => DateTime(year, 6, 6);
DateTime kdtStEphrem(int year) => DateTime(year, 6, 9);
DateTime kdtStBarnabas(int year) => DateTime(year, 6, 11);
DateTime kdtStAnthonyPadua(int year) => DateTime(year, 6, 13);
DateTime kdtStRomuald(int year) => DateTime(year, 6, 19);
DateTime kdtStAloysiusGonzaga(int year) => DateTime(year, 6, 21);
DateTime kdtStsPaulinusJohnAndThomas(int year) => DateTime(year, 6, 22);
DateTime kdtStCyrilAlexandria(int year) => DateTime(year, 6, 27);
DateTime kdtStIrenaeus(int year) => DateTime(year, 6, 28);
DateTime kdtFirstHolyMartyrs(int year) => DateTime(year, 6, 30);

DateTime kdtStJuniperoSerra(int year) => DateTime(year, 7, 1);
DateTime kdtStThomas(int year) => DateTime(year, 7, 3);
DateTime kdtUsIndependenceDay(int year) => DateTime(year, 7, 4);
DateTime kdtStAnthonyMaryZaccaria(int year) => DateTime(year, 7, 5);
DateTime kdtStMariaGoretti(int year) => DateTime(year, 7, 6);
DateTime kdtStAugustineZhaoAndCompanions(int year) => DateTime(year, 7, 9);
DateTime kdtStBenedictAbbot(int year) => DateTime(year, 7, 11);
DateTime kdtStHenry(int year) => DateTime(year, 7, 13);
DateTime kdtStKateriTekakwitha(int year) => DateTime(year, 7, 14);
DateTime kdtStBonaventure(int year) => DateTime(year, 7, 15);
DateTime kdtLadyOfCarmel(int year) => DateTime(year, 7, 16);
DateTime kdtStCamillusDeLellis(int year) => DateTime(year, 7, 18);
DateTime kdtStApollinaris(int year) => DateTime(year, 7, 20);
DateTime kdtStLawrenceBrindisi(int year) => DateTime(year, 7, 21);
DateTime kdtStMaryMagdalene(int year) => DateTime(year, 7, 22);
DateTime kdtStBridgetSweden(int year) => DateTime(year, 7, 23);
DateTime kdtStSharbel(int year) => DateTime(year, 7, 24);
DateTime kdtStJames(int year) => DateTime(year, 7, 25);
DateTime kdtStsJoachimAndAnne(int year) => DateTime(year, 7, 26);
DateTime kdtStsMarthaMaryAndLazarus(int year) => DateTime(year, 7, 29);
DateTime kdtStPeterChrysologus(int year) => DateTime(year, 7, 30);
DateTime kdtStIgnatiusOfLoyola(int year) => DateTime(year, 7, 31);

DateTime kdtStAlphonsusLiguori(int year) => DateTime(year, 8, 1);
DateTime kdtStsJulianAndEusebius(int year) => DateTime(year, 8, 2);
DateTime kdtStJohnVianney(int year) => DateTime(year, 8, 4);
DateTime kdtDedicationOfSaintMaryMajorBasilica(int year) => DateTime(year, 8, 5);
DateTime kdtTransfiguration(int year) => DateTime(year, 8, 6);
DateTime kdtStsSixtusAndCajetan(int year) => DateTime(year, 8, 7);
DateTime kdtStDominic(int year) => DateTime(year, 8, 8);
DateTime kdtStTeresaBenedicta(int year) => DateTime(year, 8, 9);
DateTime kdtStLawrence(int year) => DateTime(year, 8, 10);
DateTime kdtStClare(int year) => DateTime(year, 8, 11);
DateTime kdtStJaneFrancesDeChantel(int year) => DateTime(year, 8, 12);
DateTime kdtStsPontianAndHippolytus(int year) => DateTime(year, 8, 13);
DateTime kdtStMaximillianKolbe(int year) => DateTime(year, 8, 14);
DateTime kdtAssumptionOfBVM(int year) => DateTime(year, 8, 15);
DateTime kdtStStephenOfHungary(int year) => DateTime(year, 8, 16);
DateTime kdtStJohnEudes(int year) => DateTime(year, 8, 19);
DateTime kdtStBernard(int year) => DateTime(year, 8, 20);
DateTime kdtStPiusX(int year) => DateTime(year, 8, 21);
DateTime kdtStQueenshipOfBVM(int year) => DateTime(year, 8, 22);
DateTime kdtStRoseOfLima(int year) => DateTime(year, 8, 23);
DateTime kdtStBartholomew(int year) => DateTime(year, 8, 24);
DateTime kdtStsLouisAndJoseph(int year) => DateTime(year, 8, 25);
DateTime kdtStMonica(int year) => DateTime(year, 8, 27);
DateTime kdtStAugustine(int year) => DateTime(year, 8, 28);
DateTime kdtPassionOfStJohnTheBaptist(int year) => DateTime(year, 8, 29);

DateTime kdtStGregoryTheGreat(int year) => DateTime(year, 9, 3);
DateTime kdtNativityOfBVM(int year) => DateTime(year, 9, 8);
DateTime kdtStPeterClaver(int year) => DateTime(year, 9, 9);
DateTime kdtMostHolyNameofMary(int year) => DateTime(year, 9, 12);
DateTime kdtStJohnChrysostom(int year) => DateTime(year, 9, 13);
DateTime kdtExaltationOfCross(int year) => DateTime(year, 9, 14);
DateTime kdtLadyOfSorrows(int year) => DateTime(year, 9, 15);
DateTime kdtStsCorneliusAndCyprian(int year) => DateTime(year, 9, 16);
DateTime kdtStsHildegardAndRobert(int year) => DateTime(year, 9, 17);
DateTime kdtStJanuarius(int year) => DateTime(year, 9, 19);
DateTime kdtStsAndrewAndPaulAndCompanions(int year) => DateTime(year, 9, 20);
DateTime kdtStMatthew(int year) => DateTime(year, 9, 21);
DateTime kdtStPiusOfPietrelcina(int year) => DateTime(year, 9, 23);
DateTime kdtStsCosmasAndDamian(int year) => DateTime(year, 9, 26);
DateTime kdtStVincentDePaul(int year) => DateTime(year, 9, 27);
DateTime kdtStsWenceslausAndLawrenceAndCompanions(int year) => DateTime(year, 9, 28);
DateTime kdtStsMichaelGabrielAndRaphael(int year) => DateTime(year, 9, 29);
DateTime kdtStJerome(int year) => DateTime(year, 9, 30);

DateTime kdtStTherese(int year) => DateTime(year, 10, 1);
DateTime kdtHolyGuardianAngels(int year) => DateTime(year, 10, 2);
DateTime kdtStFrancisOfAssisi(int year) => DateTime(year, 10, 4);
DateTime kdtStFaustinaKowalska(int year) => DateTime(year, 10, 5);
DateTime kdtStBruno(int year) => DateTime(year, 10, 6);
DateTime kdtLadyOfTheRosary(int year) => DateTime(year, 10, 7);
DateTime kdtStsJohnAndDenisAndCompanions(int year) => DateTime(year, 10, 9);
DateTime kdtStJohnXXIII(int year) => DateTime(year, 10, 11);
DateTime kdtStCallistusI(int year) => DateTime(year, 10, 14);
DateTime kdtStTeresaOfJesus(int year) => DateTime(year, 10, 15);
DateTime kdtStsMargaretAndHedwig(int year) => DateTime(year, 10, 16);
DateTime kdtStIgnatiusOfAntioch(int year) => DateTime(year, 10, 17);
DateTime kdtStLuke(int year) => DateTime(year, 10, 18);
DateTime kdtStsJohnAndIsaac(int year) => DateTime(year, 10, 19);
DateTime kdtStPaulOfTheCross(int year) => DateTime(year, 10, 20);
DateTime kdtStJohnPaulII(int year) => DateTime(year, 10, 22);
DateTime kdtStJohnOfCapistrano(int year) => DateTime(year, 10, 23);
DateTime kdtStAnthonyMaryClaret(int year) => DateTime(year, 10, 24);
DateTime kdtStsSimonAndJude(int year) => DateTime(year, 10, 28);

DateTime kdtAllSaints(int year) => DateTime(year, 11, 1);
DateTime kdtAllSouls(int year) => DateTime(year, 11, 2);
DateTime kdtStMartinDePorres(int year) => DateTime(year, 11, 3);
DateTime kdtStCharlesBorromeo(int year) => DateTime(year, 11, 4);
DateTime kdtLateranBasilica(int year) => DateTime(year, 11, 9);
DateTime kdtStLeoTheGreat(int year) => DateTime(year, 11, 10);
DateTime kdtStMartinOfTours(int year) => DateTime(year, 11, 11);
DateTime kdtStJosaphat(int year) => DateTime(year, 11, 12);
DateTime kdtStFrancesXavier(int year) => DateTime(year, 11, 13);
DateTime kdtStAlbertTheGreat(int year) => DateTime(year, 11, 15);
DateTime kdtStsMargaretAndGertrude(int year) => DateTime(year, 11, 16);
DateTime kdtStElizabethOfHungary(int year) => DateTime(year, 11, 17);
DateTime kdtDedicationOfBasilicaOfStsPeterAndPaul(int year) => DateTime(year, 11, 18);
DateTime kdtPresentationOfBVM(int year) => DateTime(year, 11, 21);
DateTime kdtStCecilia(int year) => DateTime(year, 11, 22);
DateTime kdtStsMiguelAndColumbanAndClementI(int year) => DateTime(year, 11, 23);
DateTime kdtStAndrewDungLac(int year) => DateTime(year, 11, 24);
DateTime kdtStCatherineOfAlexandria(int year) => DateTime(year, 11, 25);
DateTime kdtStAndrew(int year) => DateTime(year, 11, 30);

DateTime kdtStXavier(int year) => DateTime(year, 12, 3);
DateTime kdtStJohnOfDamascus(int year) => DateTime(year, 12, 4);
DateTime kdtStNicholas(int year) => DateTime(year, 12, 6);
DateTime kdtStAmbrose(int year) => DateTime(year, 12, 7);
DateTime kdtStJuanDiego(int year) => DateTime(year, 12, 9);
DateTime kdtLadyOfLoreto(int year) => DateTime(year, 12, 10);
DateTime kdtStDamasusI(int year) => DateTime(year, 12, 11);
DateTime kdtLadyOfGuadalupe(int year) => DateTime(year, 12, 12);
DateTime kdtStLucy(int year) => DateTime(year, 12, 13);
DateTime kdtStJohnOfTheCross(int year) => DateTime(year, 12, 14);
DateTime kdtStPeterCanisius(int year) => DateTime(year, 12, 21);
DateTime kdtStJohnOfKanty(int year) => DateTime(year, 12, 23);
DateTime kdtStThomasBecket(int year) => DateTime(year, 12, 29);
DateTime kdtStSylvesterI(int year) => DateTime(year, 12, 31);

DateTime kdtImmaculateConceptionOfBVM(int year) {
  final DateTime conception = DateTime(year, 12, 8);
  return conception.weekday == DateTime.sunday ? DateTime(year, 12, 9) : conception;
}

DateTime kdtUsThanksgivingDay(int year) {
  DateTime firstDayOfMonth = DateTime(year, 11);
  DateTime firstThursday = firstDayOfMonth.add(
    Duration(days: (DateTime.thursday - firstDayOfMonth.weekday) % DateTime.daysPerWeek),
  );
  return firstThursday.add(const Duration(days: 21));
}